# Generated by Django 4.0.5 on 2024-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_customrecipe_step_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
