# Generated by Django 4.0.5 on 2023-11-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_foreignapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignapi',
            name='name',
            field=models.CharField(default='API Name', max_length=50),
        ),
    ]
