# Generated by Django 4.0.5 on 2024-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_customrecipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pe_images'),
        ),
    ]
