# Generated by Django 4.0.5 on 2024-03-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_customrecipe_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForeignAPI',
        ),
    ]
